name: lichess_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-191.0.dev

# Add regular dependencies here.
dependencies:
  dartchess: ^0.9.2
  http: ^1.2.1
  lichess_client: ^0.0.24
  ndjson: ^0.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
